#ifndef _GLOBAL_CONSTANTS_H
#define _GLOBAL_CONSTANTS_H

#define SCREEN_COLUMNS 32
#define SCREEN_ROWS 24
#define SCREEN_ROWS_FULL 28 // This might need to adjust based on PAL or NTSC?
#define SCREEN_SIZE (SCREEN_COLUMNS * SCREEN_ROWS)
#define SCREEN_SIZE_MAX (SCREEN_COLUMNS * SCREEN_ROWS_FULL)

#endif
